### ISSUE TITLE
"unexpected character" after upgrading to 1.0.5 from 0.1.8

### ISSUE THREAD

**Issue by Ugly-Wan** [leafvmaple/luadata#3]
I am getting `Unserialize luadata....unexpected character.` after updating from  `0.1.8` to `1.0.5`

```
pip3 freeze | grep lua
luadata==0.1.8
```

Error output 
```
pip3 freeze | grep lua
luadata==1.0.5

python app.py
Traceback (most recent call last):
  File "app.py", line 117, in <module>
    main()
  File "app.py", line 113, in main
    read_file('dsl-lua.txt', 'sss', 'dsl')
  File "app.py", line 32, in read_file
    dsl = luadata.read(file_name, encoding='utf-8')
  File "/usr/local/lib/python3.8/site-packages/luadata/io/read.py", line 26, in read
    return unserialize(text, encoding=encoding, multival=False)
  File "/usr/local/lib/python3.8/site-packages/luadata/serializer/unserialize.py", line 354, in unserialize
    raise Exception(
Exception: Unserialize luadata failed on pos 13:
    ={}
dsl.firmwa
        ^
    unexpected character.
```

Sample data
```
local dsl={}
dsl.line_state="UP"
dsl.get_resyncs="1"
return dsl
```

Verbose output from luadata.serializer.unserialize
```
[step] pos 0 b'l' SEEK_CHILD None None {'entries': [], 'lualen': 0, 'is_root': True}
           0      VALUE None 1 {'entries': [], 'lualen': 0, 'is_root': True}
[step] pos 0 b'l' VALUE None 1 {'entries': [], 'lualen': 0, 'is_root': True}
           1      VALUE None 1 {'entries': [], 'lualen': 0, 'is_root': True}
[step] pos 1 b'o' VALUE None 1 {'entries': [], 'lualen': 0, 'is_root': True}
           2      VALUE None 1 {'entries': [], 'lualen': 0, 'is_root': True}
[step] pos 2 b'c' VALUE None 1 {'entries': [], 'lualen': 0, 'is_root': True}
           3      VALUE None 1 {'entries': [], 'lualen': 0, 'is_root': True}
[step] pos 3 b'a' VALUE None 1 {'entries': [], 'lualen': 0, 'is_root': True}
           4      VALUE None 1 {'entries': [], 'lualen': 0, 'is_root': True}
[step] pos 4 b'l' VALUE None 1 {'entries': [], 'lualen': 0, 'is_root': True}
           5      VALUE None 1 {'entries': [], 'lualen': 0, 'is_root': True}
[step] pos 5 b' ' VALUE None 1 {'entries': [], 'lualen': 0, 'is_root': True}
           6      VALUE None 1 {'entries': [], 'lualen': 0, 'is_root': True}
[step] pos 6 b'd' VALUE None 1 {'entries': [], 'lualen': 0, 'is_root': True}
           7      VALUE None 1 {'entries': [], 'lualen': 0, 'is_root': True}
[step] pos 7 b's' VALUE None 1 {'entries': [], 'lualen': 0, 'is_root': True}
           8      VALUE None 1 {'entries': [], 'lualen': 0, 'is_root': True}
[step] pos 8 b'l' VALUE None 1 {'entries': [], 'lualen': 0, 'is_root': True}
           9      VALUE None 1 {'entries': [], 'lualen': 0, 'is_root': True}
[step] pos 9 b'=' VALUE None 1 {'entries': [], 'lualen': 0, 'is_root': True}
           10      VALUE None 1 {'entries': [], 'lualen': 0, 'is_root': True}
[step] pos 10 b'{' VALUE None 1 {'entries': [], 'lualen': 0, 'is_root': True}
           11      SEEK_CHILD None 1 {'entries': [], 'lualen': 0, 'is_root': False}
[step] pos 11 b'}' SEEK_CHILD None 1 {'entries': [], 'lualen': 0, 'is_root': False}
           12      VALUE_END None None {'entries': [[1, []]], 'lualen': 1, 'is_root': True}
[step] pos 12 b'\n' VALUE_END None None {'entries': [[1, []]], 'lualen': 1, 'is_root': True}
           13      VALUE_END None None {'entries': [[1, []]], 'lualen': 1, 'is_root': True}
[step] pos 13 b'd' VALUE_END None None {'entries': [[1, []]], 'lualen': 1, 'is_root': True}
```
For some reason it's getting confused when it has finished looking at the first line and moves on to the second.

For now I have reverted to `0.1.8` as that was the last known working version.

**Comment by Danevolent** [comment]
I had the same issue, 
I found the pattern being that the unexpected char occurred after trying to deserialise a nil field.

Replacing the nils to 'none' before deserialising resulted in success.
But I had to then scan dictionaries to change 'none' to None.

I also had to have a script convert integers and floats for all childs
