### ISSUE TITLE
Can't parse scientific notation floats

### ISSUE THREAD

**Issue by AstraLuma** [leafvmaple/luadata#7]
```
>>> luadata.unserialize('1e-06')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.10/site-packages/luadata/serializer/unserialize.py", line 354, in unserialize
    raise Exception(
Exception: Unserialize luadata failed on pos 1:
    1e-06
     ^
    unexpected character.
```

For lua 5.1: https://www.lua.org/manual/5.1/manual.html#2.1
For lua 5.3: https://www.lua.org/manual/5.3/manual.html#3.1

**Comment by karel26** [comment]
Bump

**Comment by karel26** [comment]
Proposal: change lines 184-201 into those:

```python
        elif state == "INT":
            if byte_current == b"." or byte_current == b"e":
                state = "FLOAT"
            elif byte_current is None or byte_current < b"0" or byte_current > b"9":
                data = int(sbins[pos1:pos].decode(encoding))
                if component_name == "KEY":
                    key = data
                    state = "KEY_EXPRESSION_FINISH"
                    pos = pos - 1
                elif component_name == "VALUE":
                    node_entries_append(node, key, data)
                    state = "VALUE_END"
                    key = None
                    pos = pos - 1
                data = None
        elif state == "FLOAT":
            if byte_current is None or ((byte_current < b"0" or byte_current > b"9") and byte_current != b"-" and byte_current != b"+"):
                if pos == pos1 + 1 and sbins[pos1:pos] == b".":
```
